DeKal/illuminati

build.gradle
config/checkstyle/checkstyle.xml
src/main/java/com/dawn/jat/illuminati/IlluminatiApplication.java
src/main/java/com/dawn/jat/illuminati/ServletInitializer.java
src/test/java/com/dawn/jat/illuminati/IlluminatiApplicationTests.java

- Adjust indent of checkstyle
- Remove spotbug due to conflict logger with spring-starter-web

Adjust indent of checkstyle and remove spotbug

---

build.gradle

Add release plugin to make increment

Add release plugin

---

gradle.properties

Revert wrong version name

---

cms/src/core/state/app/reducer.spec.js
cms/src/core/state/app/reducers.js

Hotfix error with redux when no state

[CMS] Hotfix error with redux when no state

---

build.gradle
src/main/java/com/dawn/jat/illuminati/AppConfiguration.java

Add Cors for all external request

[HOT-FIX] Add Cors

---

README.md
build.gradle

[#81] Fix Hot-swaping with devtools, continuous auto-restart app

---

cms/src/core/state/drawer/__tests__/reducers.spec.js
cms/src/core/state/drawer/reducers.js

Fix reducer broken due to remove default case

[Hot-fix] Fix reducer broken due to remove default case

---

src/main/java/com/dawn/jat/illuminati/cms/controller/CmsController.java

#102 Add @RequestMapping supports wildcards

[#102] Fix route cms/* does not lead to cms

---

README.md
cms/README.md

[#101] Update README

---

cms/src/core/components/Drawer.js
cms/src/core/components/NavBar.js
cms/src/core/components/PageSwitch.js
cms/src/core/components/__tests__/Drawer.spec.js
cms/src/core/components/__tests__/NavBar.spec.js
cms/src/core/components/__tests__/__snapshots__/App.spec.js.snap
cms/src/core/components/__tests__/__snapshots__/Drawer.spec.js.snap
cms/src/core/components/__tests__/__snapshots__/PageSwitch.spec.js.snap
cms/src/core/const/pages.js
cms/src/core/containers/Drawer.js
cms/src/core/theme/theme.js

[#109] Improve Drawer

---

.scrutinizer.yml

[Hot-enhance] Enhance Scrutinizer config

---

cms/package.json
cms/src/core/init/initStore.js
cms/src/core/state/configureStore.js
cms/src/index.js
cms/yarn.lock

- Drawer open state will be persisted
- Add redux-persist

[#111] Drawer open state will be persisted

---

cms/src/core/components/Loading.js
cms/src/core/components/__tests__/Loading.spec.js
cms/src/core/components/__tests__/__snapshots__/Loading.spec.js.snap
cms/src/core/components/page/Container.js
cms/src/core/theme/theme.js
cms/src/posts/components/Posts.js
cms/src/posts/components/__tests__/Posts.spec.js
cms/src/posts/components/__tests__/__snapshots__/Posts.spec.js.snap

- Add loading component when requesting server

[#130]: Add loading component when requesting server

---

src/main/java/com/dawn/jat/illuminati/cms/controller/CmsController.java

- Fix cms/ using ** instead of * 
- Remove route / to cms (Route / will lead to Login page later)

[Hot-fix] Fix cms/ using ** instead of * and remove route / to cms

---

CHANGELOG.md
build.gradle
release.sh

[UPDATE] Update release

---

build.gradle

[UPDATE] Update release 2 (test)

---

build.gradle

[UPDATE] update-release-3

---

src/main/java/com/dawn/jat/illuminati/WebSecurityConfig.java
src/main/resources/application-prod.properties
src/main/resources/application-staging.properties
src/main/resources/application.properties

- Disable CSRF in case of Post request
- This is temporary until we sort out the problem at front end

[#210] Disable CSRF

---

.scrutinizer.yml

- Trying to use sonar cloud for code quality as @thuyvy3110 suggestion

[Update] Remove code quality from Scrutinize and try sonar cloud

---

src/main/resources/static/login/css/main.css
src/main/resources/templates/cms/index.html

[Sonar] Fix potential HTML bugs

---

build.gradle
src/main/java/com/dawn/jat/illuminati/core/config/AppConfig.java
src/main/java/com/dawn/jat/illuminati/core/mapper/Converter.java
src/main/java/com/dawn/jat/illuminati/core/response/ErrorResponse.java
src/main/java/com/dawn/jat/illuminati/docs/config/SpringFoxConfig.java
src/main/java/com/dawn/jat/illuminati/docs/entity/PostSummariesResponse.java
src/main/java/com/dawn/jat/illuminati/login/entity/User.java
src/main/java/com/dawn/jat/illuminati/login/provider/UserAuthenticationProvider.java
src/main/java/com/dawn/jat/illuminati/login/repository/LoginRepository.java
src/main/java/com/dawn/jat/illuminati/login/service/LoginService.java
src/main/java/com/dawn/jat/illuminati/post/controller/PostController.java
src/main/java/com/dawn/jat/illuminati/post/dto/PostDto.java
src/main/java/com/dawn/jat/illuminati/post/entity/PostEntity.java
src/main/java/com/dawn/jat/illuminati/post/repository/PostRepository.java
src/main/java/com/dawn/jat/illuminati/post/service/PostService.java
src/test/java/com/dawn/jat/illuminati/core/mapper/ConverterTest.java
src/test/java/com/dawn/jat/illuminati/post/controller/PostControllerTest.java
src/test/java/com/dawn/jat/illuminati/post/service/PostServiceTest.java

Refactor code

---

cms/src/core/utils/__test__/misc.spec.js
cms/src/core/utils/misc.js
cms/src/error/components/Error.js
cms/src/error/components/base/Layout.js
cms/src/error/components/base/__tests__/__snapshots__/Layout.spec.js.snap

- Improve error boundary
- Improve misc arrayToObject and add test

[Improve] Improve error boundary

---

cms/src/post/state/__tests__/reducers.spec.js
cms/src/post/state/reducers.js

- Remove arrayToMap when receiving payload for post detail

[Remove] Remove arrayToMap when receiving payload for post detail
